name: CI

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.4.0
      with:
        # Coverage command to execute
        CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
        coverageCommand: yarn coverage
