name: Report Code Coverage

on: [push, pull_request]

env:
  CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}

jobs:
  coverage:
    name: Test and report coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 12

      - run: yarn install
        working-directory: music-app

      - uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn --cwd music-app coverage
          coverageLocations: "music-app"
          debug: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
