name: Report Code Coverage

on: [push, pull_request]

env:
  CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}

jobs:
  test:
    name: Test and Calculate Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: yarn install
        working-directory: music-app
      - name: calculate
        uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn --cwd music-app coverage
          coverageLocations: "music-app"
