name: Report Code Coverage

on: [push, pull_request]

env:
  SW_DISABLED: true
  COVERAGE: true
  CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
  CI: true

jobs:
  test:
    name: Test and Calculate Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        run: ls && yarn install
      - name: calculate
        uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn test
