# name: Report Code Coverage

# on: [push, pull_request]

# env:
#   CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}

# jobs:
#   coverage:
#     name: Test and report coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master

#       - uses: actions/setup-node@master
#         with:
#           node-version: 12

#       - run: yarn install
#         working-directory: music-app

#       - uses: paambaati/codeclimate-action@v2.4.0
#         with:
#           coverageCommand: yarn --cwd music-app coverage
#           coverageLocations: "music-app/coverage/lcov.info:lcov"
#           debug: true
#         env:
#           CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}

name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [12,10]
    name: Test ${{ matrix.os}}/${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run build --if-present
      - run: yarn test
        env:
          CI: true
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          CI: true
        with:
          coverageCommand: yarn run coverage
          debug: true